console.log("Hello world");
console.log("Hola mundo");
console.log("Hola món");
console.log("salve mundi");
console.log("Bonjour le monde");
console.log("Ciao mondo");
console.log("Hallo Wereld");
console.log("Hello Wéreld");
console.log("Boh Diayeh");
console.log("Halló Heimur");
